version: '3.3'

volumes:
  postgres_data:
  staticfiles:
  mediafiles: 


services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: basil087/foodgram:latest
    restart: always
    command: gunicorn foodgramsite.wsgi:application --bind 0.0.0.0:5000 
    volumes:
      - staticfiles:/code/static/
      - mediafiles:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - staticfiles:/code/static/
      - mediafiles:/code/media/
    links:
      - web
