# Generated by Django 3.1.4 on 2020-12-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20201220_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(choices=[
                ('breakfast', 'Завтрак'),
                ('lunch', 'Обед'),
                ('dinner', 'Ужин'),
                ('salads', 'Салаты')],
                max_length=20, verbose_name='Название тэга'),
        ),
    ]
